### ISSUE TITLE
different decision statements with the same behavior!!

### ISSUE THREAD

**Issue by Eslam3bed** [facg3/newsServer#26]
https://github.com/facg3/newsServer/blob/59a974aa39156905271bdaf4fb0f588fc3316230/back-end-src/router.js#L8

https://github.com/facg3/newsServer/blob/59a974aa39156905271bdaf4fb0f588fc3316230/back-end-src/router.js#L11

both handle the (request and the response objects) to the  ` handlers.publicFileHandler(req, res)`

**Comment by sultanassi95** [comment]
but eachone has a different endpoint ^^", if there is another way doing it, u can point at it :+1:

**Comment by Eslam3bed** [comment]
becuase of the your app structure 
and the separating the front end files into to differant files (`front-end-src` , `public`), you did this 
but at least you could do : 
```javascript
else if(endpoint.startsWith('/front-end-src') || endpoint.startsWith('/public'))
handlers.publicFileHandler(req, res)
```
